"""empty message

Revision ID: ca77c8990f79
Revises: b9a84d84e212
Create Date: 2026-03-24 21:51:15.218053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca77c8990f79'
down_revision = 'b9a84d84e212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('IMAGE', 'VIDEO', name='mediatype'),
               type_=sa.String(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=5),
               type_=postgresql.ENUM('IMAGE', 'VIDEO', name='mediatype'),
               existing_nullable=False)

    # ### end Alembic commands ###
